/// Generated file. Do not edit.
/// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class DefaultRes {
  DefaultRes._();

  static const   PLUGIN_NAME = 'spotify_prj';
  static const   PLUGIN_VERSION = '1.0.0+1';
  static const String = '.env';
}
